### ISSUE TITLE
Adding a filter by genre

### ISSUE THREAD

**Issue by kmkrebs** [rj1/rofimpd#1]
Thanks for this -- I like the simplicity and have it tied to a hotkey in my i3 config.
I'm not too familiar with using git, but I've edited your code locally to add an option to search by genre as well.  Maybe you'd like to add it?

The code I've added:
```
modes="current playlist\nplaylists\nshuffle\ntracks\nalbums\nartists\ngenres"
```
And...
```
# list of genres
elif [[ "$mode" == "genres" ]]; then

  # list genres
  genre="$(mpc list genre | sort -f | launcher "choose a genre: ")"
  [ ! ${genre} ] && exit

  # list albums from chosen genre
  album="$(mpc list album genre "${genre}" | launcher "choose album: ")"
  [ ! ${album} ] && exit

  mpc clear
  mpc find genre "$genre" album "$album" | mpc add
  mpc play
```

**Comment by rj1** [comment]
good idea, I added it

thanks!

Quoting kmkrebs (2022-12-07 18:23:56)
